on:
  workflow_dispatch:
    inputs:
      package_version:
        description: 'Package version to be published to NPM'
        required: true

name: Build

jobs:
  prebuild-node:
    name: Upload Node Prebuild
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # using older ubuntu to mitigate "/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found" error
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          repository: "JoshuaWise/better-sqlite3"
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install npe globally
        run: npm i npe -g
      - run: npm install && (npm list || true)
      - name: Change package name
        # We're cloning better-sqlite3 here and republishing it under a different name (with prebuilt binaries).
        # Version is set manually, because sometimes we need to release new versions for the same version of better-sqlite3
        # major.minor should be kept. e.g. better-sqlite3@7.1.2 can be released as better-sqlite3-with-prebuilds 7.1.5,
        # but not 7.2.0.
        run: npe name "better-sqlite3-with-prebuilds-latest" \
          && npe repository.url "git+https://github.com/kyoto44/better-sqlite3-with-prebuilds.git" \
          && npe version "${{ github.event.inputs.package_version }}"
        # At this time, better-sqlite3 uses prebuild-install@5, which is incompatible with
        # npm@7. NPM 7 users don't get our prebuilt binaries at all and their builds are failing.
        # So in our package, we replace the version with the compatible one.
      - name: Bump prebuild-install version
        run: npe "dependencies.prebuild-install" "^6.0.1"
      - name: Show package.json
        run: cat package.json
      - name: Build release
        run: |
          node ./node_modules/prebuild/bin.js -r node -t 14.0.0 -t 15.0.0 -t 16.0.0 --include-regex 'better_sqlite3.node$' -u ${{ secrets.GITHUB_TOKEN }}
          node ./node_modules/prebuild/bin.js -r node -t 14.0.0 -t 15.0.0 -t 16.0.0 --include-regex 'better_sqlite3.node$' --arch ia32 -u ${{ secrets.GITHUB_TOKEN }}
